# Generated by Django 4.1 on 2022-09-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0002_rename_area_text_fact_fact_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_text', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='value',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.unit'),
        ),
    ]
