# Generated by Django 4.1 on 2022-09-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0003_unit_alter_value_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knu.unit'),
        ),
    ]
