# Generated by Django 4.1 on 2022-09-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0004_alter_value_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='unit',
        ),
    ]
