# Generated by Django 4.1 on 2022-09-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0006_value_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_txt', models.CharField(max_length=20)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.dimension')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.value')),
            ],
        ),
    ]
