# Generated by Django 4.1 on 2022-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0007_dimension_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_text',
            field=models.CharField(max_length=40),
        ),
    ]
