# Generated by Django 3.2.15 on 2022-10-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0008_alter_fact_fact_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_text', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('inheritance', models.ManyToManyField(related_name='_knu_scenario_inheritance_+', to='knu.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_text', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.scenario')),
            ],
        ),
    ]
