# Generated by Django 3.2.15 on 2022-10-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0010_auto_20221023_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knu.scenario'),
            preserve_default=False,
        ),
    ]
