# Generated by Django 3.2.15 on 2022-10-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0012_alter_value_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='knu.scenario'),
        ),
    ]
