# Generated by Django 3.2.15 on 2022-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0014_alter_fact_fact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_text',
            field=models.CharField(max_length=40),
        ),
    ]
