# Generated by Django 3.2.15 on 2022-10-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0016_alter_value_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('method', models.CharField(default='', max_length=200)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.fact')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('calculation_text', models.CharField(max_length=40)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
