# Generated by Django 3.2.15 on 2022-10-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0017_auto_20221024_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_text', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SelectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_txt', models.CharField(max_length=20)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.dimension')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.result')),
            ],
        ),
        migrations.CreateModel(
            name='SelectEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_txt', models.CharField(max_length=20)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.dimension')),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.eval')),
            ],
        ),
        migrations.AddField(
            model_name='eval',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knu.task'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knu.task'),
            preserve_default=False,
        ),
    ]
