# Generated by Django 3.2.15 on 2022-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knu', '0018_auto_20221024_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='prio',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
